version: '3'
services:
  microplastics-backend:
    container_name: microplastics-backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
