version: "3"
services:
  microplastics-backend:
    container_name: microplastics-backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - media-data:/app/media
    ports:
      - "3000:3000"

volumes:
  media-data:
