[supervisord]
nodaemon=true
pidfile=/dev/null
logfile=/dev/null
logfile_maxbytes=0
loglevel=info

[program:fastapi]
command=uvicorn main:app --host 0.0.0.0 --port 3000 --workers 4
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:cron]
command=cron -f
autostart=true
autorestart=true
stdout_logfile=/var/log/cron.log
stderr_logfile=/var/log/cron_error.log
