INSERT INTO microplastic_zones (
    polygon_id,
    polygon_geom,
    NDVI,
    NDWI,
    NDCI,
    FDI,
    NDPI,
    BLUE,
    GREEN,
    RED,
    REDEDGE1,
    REDEDGE2,
    REDEDGE3,
    NIR_10m,
    NIR_20m,
    SWIR1,
    SWIR2,
    pred_linear,
    pred_forest,
    pred_neural,
    created_at
) VALUES (
    %s,
    ST_GeomFromText(%s, 4326),
    %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s,
    %s, %s, %s, %s, %s,
    %s, %s, %s,
    %s
);